# Generated by Django 3.2.16 on 2023-03-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='imag_path',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
