# Generated by Django 4.0.6 on 2023-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20230302_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='classes',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
