# Generated by Django 3.2.16 on 2023-03-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_rename_user_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='classes',
            field=models.CharField(default='NA', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='imag_path',
            field=models.CharField(default='NA', max_length=10000),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.CharField(default='NA', max_length=1000),
        ),
    ]
