# Generated by Django 4.0.6 on 2023-03-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_id', models.CharField(default='NA', max_length=200)),
                ('user', models.CharField(default='NA', max_length=200)),
                ('imgCount', models.CharField(default='NA', max_length=200)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(default='NA', max_length=200)),
                ('classes', models.CharField(default='NA', max_length=500)),
                ('imag_path', models.CharField(default='NA', max_length=1000)),
                ('owner_name', models.CharField(default='NA', max_length=200)),
                ('members', models.CharField(default='NA', max_length=1000)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
